version: '2'
services:
    angela-app:
        image: angela
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angela-mysql:3306/angela?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angela-mysql:
        extends:
            file: mysql.yml
            service: angela-mysql
